spring:
  application:
    name: axon-sample
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id:
            client-secret:
            provider: keycloak
            scope: openid
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          keycloak:
            authorization-uri: http://localhost:18080/realms/sample/protocol/openid-connect/auth
            token-uri: http://localhost:18080/realms/sample/protocol/openid-connect/token
            user-info-uri: http://localhost:18080/realms/sample/protocol/openid-connect/userinfo
            jwk-set-uri: http://localhost:18080/realms/sample/protocol/openid-connect/certs
            issuer-uri: http://localhost:18080/realms/sample
            user-name-attribute: preferred_username
axon:
  axonserver:
    enabled: false
  serializer:
    general: jackson3
    events: jackson3
    messages: jackson3
